### ISSUE TITLE
Documentation 3.x : missing information into "2.10   Repositories settings" chapter

### ISSUE THREAD

**Issue by robotccm** [ccmbenchmark/ting#36]
**[Original report](https://bitbucket.org/ccmbenchmark/ting/issue/36) by Nicolas Desaleux (Bitbucket: [Nicolas Desaleux](https://bitbucket.org/Nicolas Desaleux), ).**

----------------------------------------

```
#!yml

ting:
    repositories:
        World:
            namespace: AppBundle\Repository
            directory: "@AppBundle/Repository"
            glon: "*.php" # missing this line (does not work with current repositories filename does not contains Repository (default value)
            options:
                default:
                    connection: main
                    database: world
```
